=== nioomeee/Sem-3-Assignments-1/XML/Assignment_2/dtd/5_Books.dtd
<!ELEMENT Books (Book+)>
<!ELEMENT Book (author , year , publisher )>
<!ATTLIST Book title (XML | DCN) #REQUIRED>
<!ELEMENT author (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>

=== nioomeee/Sem-3-Assignments-1/XML/Assignment_2/5_Books.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Books SYSTEM "dtd/5_Books.dtd">
<Books>
    <Book title="XML">
        <author>Author Name 1</author>
        <year>2024</year>
        <publisher>Publisher Name 1</publisher>
    </Book>
    <Book title="DCN">
        <author>Author Name 2</author>
        <year>2023</year>
        <publisher>Publisher Name 2</publisher>
    </Book>
</Books>
