=== nioomeee/Sem-3-Assignments-1/XML/Assignment_2/dtd/7_Email.dtd
<!ELEMENT Email (From, To, Content)+>
<!ELEMENT From (#PCDATA)>
<!ELEMENT To (#PCDATA)>
<!ELEMENT Content (#PCDATA | Person | Exercises)*>
<!ELEMENT Person (#PCDATA)>
<!ELEMENT Exercises (Exercise, Course)>
<!ELEMENT Course (#PCDATA)>
<!ELEMENT Exercise (Topic, Description)>
<!ELEMENT Topic (#PCDATA)>
<!ELEMENT Description (#PCDATA)>

=== nioomeee/Sem-3-Assignments-1/XML/Assignment_2/7_Email.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE Email SYSTEM "dtd/7_Email.dtd">
<Email>
    <From>vansh</From>
    <To>sarthak</To>
    <Content>
        <Person>Hello</Person>
        <Exercises>
            <Exercise>
                <Topic>Assignment</Topic>
                <Description>Do the tasks by tomorrow</Description>
            </Exercise>
            <Course>XYZ</Course>
        </Exercises>
    </Content>
    <From>vansh</From>
    <To>sarthak</To>
    <Content>
        Hey no worries that will be finished by tomorrow
    </Content>
</Email>
