=== nioomeee/Sem-3-Assignments-1/XML/Assignment_2/dtd/8_Student.dtd
<!ELEMENT Student (Roll_no, Name, Marks, Rank)>
<!ELEMENT Roll_no (#PCDATA)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Marks (web_technologies, XML, J2EE, NS)>
<!ELEMENT web_technologies (#PCDATA)>
<!ELEMENT XML (#PCDATA)>
<!ELEMENT J2EE (#PCDATA)>
<!ELEMENT NS (#PCDATA)>
<!ELEMENT Rank (#PCDATA)>

=== nioomeee/Sem-3-Assignments-1/XML/Assignment_2/8_Student.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Student SYSTEM "dtd/8_Student.dtd">
<Student>
    <Roll_no>12345</Roll_no>
    <Name>Rahul Sharma</Name>
    <Marks>
        <web_technologies>85</web_technologies>
        <XML>90</XML>
        <J2EE>88</J2EE>
        <NS>92</NS>
    </Marks>
    <Rank>1</Rank>
</Student>
